server:
  port: 8081
  servlet:
    context-path: /cache
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true # 是否在控制台打印SQL语句
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 600000ms
    cache-names: userCache,allUsersCache #Creates additional caches on startup.
  redis:
    host: localhost
    port: 6379
    # springBoot2.0的redis客户端
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
    database: 0
