server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shiro-sba
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true # 是否在控制台打印SQL语句
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true